version: "3.8"
services:

  gbotj-dev:
    container_name: "GBotJ_dev"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "5005:5005"
      - "5003:5004"